version: '3.8'
services:
  web:
    network_mode: "host"
    build: .
    command: >
      sh -c "python3.11 manage.py collectstatic --noinput &&
             python3.11 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1  # Установи это значение в зависимости от окружения
    volumes:
      - ./:/code
      - ./registr_page/.env:/code/registr_page/registr_page/.env
